import { LocationPageTemplate } from "@/components/location-page-template"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Organic Waste Converter Machine Suppliers in Kerala | OWC Machine Kerala - Solwearth",
  description: "Leading organic waste converter machine suppliers in Kerala. Energy-effective OWC machines with no emissions for hotels, resorts, hospitals. Home state expertise. Easy installation. Call +91 98950 44004.",
  keywords: "organic waste converter Kerala, organic waste converter machine suppliers Kerala, OWC machine Kerala, food waste converter machine Kerala, automatic organic waste converter Kerala, waste management solutions Kerala, composting machine Kerala, OWC suppliers Kerala, organic waste management Kerala, waste converter Kochi",
  openGraph: {
    title: "Organic Waste Converter Machine Suppliers in Kerala - Solwearth Ecotech",
    description: "Kerala's trusted organic waste converter suppliers. Cost and energy-effective machines with zero emissions. Local expertise and support. Serving hotels, resorts, hospitals, and institutions across Kerala.",
    type: 'website',
  },
  alternates: {
    canonical: "https://www.solwearth.com/locations/india/kerala"
  }
}

export default function KeralaPage() {
  return (
    <LocationPageTemplate
      title="Organic Waste Converter Machine Suppliers in Kerala"
      subtitle="Home State Expertise with Regional Solutions"
      location="Kerala, India"
      description={[
        "Kerala, fondly known as 'God's Own Country,' has always been at the forefront of environmental sustainability and green initiatives in India. As Solwearth Ecotech's home state, Kerala holds a special place in our mission to promote sustainable waste management. Our headquarters in Kerala enables us to provide comprehensive regional solutions with unmatched local expertise, quick response times, and a deep understanding of the state's unique environmental values and regulations.",
        "Our organic waste converter machines in Kerala are designed to be cost and energy-effective, featuring zero emissions, no smoke, and completely odor-free operation. These characteristics align perfectly with Kerala's commitment to maintaining its pristine natural environment while managing the waste generated by its booming tourism and hospitality sectors. Easy installation and low maintenance requirements make our machines ideal for establishments across the state, from the backwaters of Alleppey to the hills of Munnar.",
        "Beyond organic waste converters, Solwearth Ecotech offers a comprehensive range of eco-friendly products including water conservation systems, solar panels, and energy-efficient lighting solutions. This holistic approach to sustainability reflects our company's mission of social commitment and environmental responsibility, values deeply rooted in Kerala's progressive environmental consciousness.",
      ]}
      benefits={[
        "Cost and energy-effective operation for maximum ROI",
        "Zero emissions, smoke, or odor during processing",
        "Easy installation process with no special requirements",
        "Low maintenance requirements with durable construction",
        "Strong support for Kerala's green initiatives and policies",
        "Local expertise and rapid support from our home state team",
        "Additional eco-friendly products available for comprehensive solutions",
        "Deep commitment to social responsibility and sustainability",
        "Perfect for Kerala's environmentally conscious establishments",
        "Aligned with Kerala's waste management regulations and goals",
      ]}
      targetMarket={[
        "Hotels, Resorts & Ayurveda Centers",
        "Restaurants, Cafes & Catering Services",
        "Residential Communities & Apartment Complexes",
        "Hospitals, Clinics & Healthcare Facilities",
        "Educational Institutions & University Campuses",
        "Tourist Facilities & Houseboats",
        "Catering Services & Event Venues",
        "Government Institutions & Public Offices",
        "IT Parks & Business Centers",
        "Food Processing Units & Manufacturing",
      ]}
      features={[
        "Multi-stage indirect heat and dry decomposition technology",
        "Capacity range: 40 KG to 1000 KG per batch (SE-501 to SE-1H models)",
        "Processing time: 12-24 hours depending on waste type and capacity",
        "83-90% average waste volume reduction through dehydration",
        "Zero emission - No exhaust system or chimney required",
        "Fully automatic PLC control with user-friendly interface",
        "Integrated deodorization for completely odor-free operation",
        "Durable stainless steel construction for hygiene and longevity",
        "No additives, bacteria, enzymes, or chemicals required",
        "1-year comprehensive warranty with local service support",
      ]}
    />
  )
}
